version: '3.2'
services:
  db:
    container_name: postgres
    image: postgres:10.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
  web:
    container_name: blockscout
    build:
      context: .
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - ETHEREUM_JSONRPC_VARIANT=geth
      - ETHEREUM_JSONRPC_HTTP_URL=https://mainnet.infura.io/8lTvJTKmHPCHazkneJsY
      - COIN=ETH
      - MIX_ENV=prod
      - PORT=4000
      - SECRET_KEY_BASE=RMgI4C1HSkxsEjdhtGMfwAHfyT6CKWXOgzCboJflfSm4jeAlic52io05KB6mqzc5
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
    depends_on:
      - db

    command:
      - ./run.sh